### ISSUE TITLE
site scales poorly

### ISSUE THREAD

**Issue by d4l3k** [startupstorm/startupstorm.github.io#5]
![2017-09-10-195958_1919x991_scrot](https://user-images.githubusercontent.com/909104/30256866-b2e0fa80-9662-11e7-8a91-a96cd1da833a.png)

If you view it on a high-resolution screen/zoom in/out it gets all messed up. There's something weird going on with how text is positioned on the background.

**Comment by chamkank** [comment]
Zooming in works fine for me but I notice that this layout problem happens when you zoom out any further than 90% screen width (happens on all devices). Just curious, what device/browser did you test this on?

**Comment by d4l3k** [comment]
Zooming in works fine mostly, just saying that the background and text don't match. That screenshot is at like 33% zoom, but it's weird on my laptop at 100% zoom.

Chrome, Linux, 1080p screen

**Comment by chamkank** [comment]
That's strange, I'm on Chrome, Windows, 1080p screen and it works for me on 100% zoom - not sure what's going on but I'll see if I can find the issue.

**Comment by d4l3k** [comment]
Any updates on this? @chamkank

**Comment by chamkank** [comment]
Yeah, I'll fix it by the end of this weekend.

**Comment by chamkank** [comment]
Done (https://github.com/startupstorm/startupstorm.github.io/commit/234c1e5a6c88d0d82c409a7decff40842dce2553)
